name: Build and deploy a container to an Azure Web App

env:
  AZURE_WEBAPP_NAME: MyHelloWordDockerApp  # set this to the name of your Azure Web App

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build & Push Docker Image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Docker image tag
        id: tag
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag forsanta/webapi-starter-dotnet8:latest
      - name: Push Docker image
        run: |
          docker push forsanta/webapi-starter-dotnet8:latest

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DOCKER }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
