name: Build, test and push Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/webapi-demo:latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore MyWebApi/MyWebApi.csproj

    - name: Build project
      run: dotnet build MyWebApi/MyWebApi.csproj -c Release --no-restore

    - name: Run tests if present
      run: |
        if ls **/*Tests.csproj 1> /dev/null 2>&1; then
          dotnet test MyWebApi/MyWebApi.csproj --no-build --verbosity normal
        else
          echo "No test projects found, skipping tests."
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.DOCKER_IMAGE }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
