name: Verify or Create Azure Web App

on:
  workflow_call:
    inputs:
      runtime:
        required: true
        type: string
      webapp-name:
        required: true
        type: string
      resource-group:
        required: true
        type: string

jobs:
  verify-create-webapp:
    runs-on: ubuntu-latest
    outputs:
      publish-profile: ${{ steps.get-publish-profile.outputs.profile }}

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check if Web App exists
        id: check-webapp
        run: |
          exists=$(az webapp show --name ${{ inputs.webapp-name }} --resource-group ${{ inputs.resource-group }} --query "name" -o tsv || echo "")
          echo "exists=$exists" >> $GITHUB_OUTPUT

      - name: Create Web App if not exists
        if: steps.check-webapp.outputs.exists == ''
        run: |
          echo "Web App not found, creating..."
          az webapp create \
            --name ${{ inputs.webapp-name }} \
            --resource-group ${{ inputs.resource-group }} \
            --plan ${{ inputs.resource-group }}-plan \
            --runtime "DOTNET|${{ inputs.runtime }}" \
            --output none

      - name: Get publish profile
        id: get-publish-profile
        run: |
          profile=$(az webapp deployment list-publishing-profiles \
            --name ${{ inputs.webapp-name }} \
            --resource-group ${{ inputs.resource-group }} \
            --xml)
          echo "profile<<EOF" >> $GITHUB_OUTPUT
          echo "$profile" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
